//clouds
export const REQUEST_CLOUDS = "REQUEST_CLOUDS";
export const REQUEST_CLOUDS_FINISHED = "REQUEST_CLOUDS_FINISHED";
export const SET_CLOUDS = "SET_CLOUDS";

//platforms
export const REQUEST_PLATFORMS = "REQUEST_PLATFORMS";
export const REQUEST_PLATFORMS_FINISHED = "REQUEST_PLATFORMS_FINISHED";
export const SET_PLATFORMS = "SET_PLATFORMS";

//location
export const SET_USER_LOCATION = "SET_USER_LOCATION";
